//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.SystemInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.SystemInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address width.
        /// </summary>
        internal static string SystemInfo_AddressWidth {
            get {
                return ResourceManager.GetString("SystemInfo_AddressWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application up time.
        /// </summary>
        internal static string SystemInfo_ApplicationUpTime {
            get {
                return ResourceManager.GetString("SystemInfo_ApplicationUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Architecture.
        /// </summary>
        internal static string SystemInfo_Architecture {
            get {
                return ResourceManager.GetString("SystemInfo_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available memory.
        /// </summary>
        internal static string SystemInfo_AvailableMemory {
            get {
                return ResourceManager.GetString("SystemInfo_AvailableMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build.
        /// </summary>
        internal static string SystemInfo_Build {
            get {
                return ResourceManager.GetString("SystemInfo_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bus speed (Mhz).
        /// </summary>
        internal static string SystemInfo_BusSpeedMhz {
            get {
                return ResourceManager.GetString("SystemInfo_BusSpeedMhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clock speed (Mhz).
        /// </summary>
        internal static string SystemInfo_ClockSpeedMhz {
            get {
                return ResourceManager.GetString("SystemInfo_ClockSpeedMhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU info.
        /// </summary>
        internal static string SystemInfo_CpuInfo {
            get {
                return ResourceManager.GetString("SystemInfo_CpuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU name.
        /// </summary>
        internal static string SystemInfo_CpuName {
            get {
                return ResourceManager.GetString("SystemInfo_CpuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current culture.
        /// </summary>
        internal static string SystemInfo_CurrentCulture {
            get {
                return ResourceManager.GetString("SystemInfo_CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data width.
        /// </summary>
        internal static string SystemInfo_DataWidth {
            get {
                return ResourceManager.GetString("SystemInfo_DataWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string SystemInfo_Description {
            get {
                return ResourceManager.GetString("SystemInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Framework versions.
        /// </summary>
        internal static string SystemInfo_DotNetFrameworkVersions {
            get {
                return ResourceManager.GetString("SystemInfo_DotNetFrameworkVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed database providers.
        /// </summary>
        internal static string SystemInfo_InstalledDatabaseProviders {
            get {
                return ResourceManager.GetString("SystemInfo_InstalledDatabaseProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Machine name.
        /// </summary>
        internal static string SystemInfo_MachineName {
            get {
                return ResourceManager.GetString("SystemInfo_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. process RAM.
        /// </summary>
        internal static string SystemInfo_MaxProcessRam {
            get {
                return ResourceManager.GetString("SystemInfo_MaxProcessRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на n/a.
        /// </summary>
        internal static string SystemInfo_NotAvailable {
            get {
                return ResourceManager.GetString("SystemInfo_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of cores.
        /// </summary>
        internal static string SystemInfo_NumberOfCores {
            get {
                return ResourceManager.GetString("SystemInfo_NumberOfCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of logical processors.
        /// </summary>
        internal static string SystemInfo_NumberOfLogicalProcessors {
            get {
                return ResourceManager.GetString("SystemInfo_NumberOfLogicalProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OS info.
        /// </summary>
        internal static string SystemInfo_OsInfo {
            get {
                return ResourceManager.GetString("SystemInfo_OsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OS name.
        /// </summary>
        internal static string SystemInfo_OsName {
            get {
                return ResourceManager.GetString("SystemInfo_OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OS version.
        /// </summary>
        internal static string SystemInfo_OsVersion {
            get {
                return ResourceManager.GetString("SystemInfo_OsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processor ID.
        /// </summary>
        internal static string SystemInfo_ProcessorId {
            get {
                return ResourceManager.GetString("SystemInfo_ProcessorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System up time.
        /// </summary>
        internal static string SystemInfo_SystemUpTime {
            get {
                return ResourceManager.GetString("SystemInfo_SystemUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total memory.
        /// </summary>
        internal static string SystemInfo_TotalMemory {
            get {
                return ResourceManager.GetString("SystemInfo_TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User domain name.
        /// </summary>
        internal static string SystemInfo_UserDomainName {
            get {
                return ResourceManager.GetString("SystemInfo_UserDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        internal static string SystemInfo_UserName {
            get {
                return ResourceManager.GetString("SystemInfo_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string SystemInfo_Version {
            get {
                return ResourceManager.GetString("SystemInfo_Version", resourceCulture);
            }
        }
    }
}
