//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.SystemInfo.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.SystemInfo.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU ID.
        /// </summary>
        internal static string SystemInfoExample_CpuId {
            get {
                return ResourceManager.GetString("SystemInfoExample_CpuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU ID.
        /// </summary>
        internal static string SystemInfoExample_GpuId {
            get {
                return ResourceManager.GetString("SystemInfoExample_GpuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard drive ID.
        /// </summary>
        internal static string SystemInfoExample_HardDriveId {
            get {
                return ResourceManager.GetString("SystemInfoExample_HardDriveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine ID.
        /// </summary>
        internal static string SystemInfoExample_MachineId {
            get {
                return ResourceManager.GetString("SystemInfoExample_MachineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac ID.
        /// </summary>
        internal static string SystemInfoExample_MacId {
            get {
                return ResourceManager.GetString("SystemInfoExample_MacId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherboard ID.
        /// </summary>
        internal static string SystemInfoExample_MotherboardId {
            get {
                return ResourceManager.GetString("SystemInfoExample_MotherboardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System identification.
        /// </summary>
        internal static string SystemInfoExample_SystemIdentificationTab {
            get {
                return ResourceManager.GetString("SystemInfoExample_SystemIdentificationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System info.
        /// </summary>
        internal static string SystemInfoExample_SystemInfoTab {
            get {
                return ResourceManager.GetString("SystemInfoExample_SystemInfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on it....
        /// </summary>
        internal static string SystemInfoExample_WorkingOnIt {
            get {
                return ResourceManager.GetString("SystemInfoExample_WorkingOnIt", resourceCulture);
            }
        }
    }
}
